#!/usr/bin/env bash
# popong-start -- start components to bring our service up
# Usage: popong start
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2011-08-20
set -u

cd "$POPONG_SVCROOT"

# prepare dirs
mkdir -p log run

#TODO # start db
#TODO synchronized run/db.lock engine &>log/db.log &

# start webserver
synchronized run/webserver.lock webserver "$@" &

disown
