#!/usr/bin/env bash
# webserver -- Start a web server for POPONG
# 
# Usage: webserver [PORTNUM]
# 
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2011-08-20
set -eu

# User input
: ${Port:=8765}
[ $# -eq 0 ] || { Port=$1; shift; }

# Try next available port if already being used
while netstat -an | grep -q '[.:]'$Port' .*LISTEN'; do
    let Port++
done

# Prepare web server config
conf="$POPONG_SVCROOT/etc/lighttpd.conf"
{
    cat <<-EOF
	server.port                 = $Port
	server.document-root        = "$POPONG_SVCROOT/www/"
	server.modules              = ( "mod_alias"
	                              , "mod_accesslog"
	                              , "mod_rewrite"
	                              )
	
	server.errorlog             = "$POPONG_SVCROOT/log/webserver.error.log"
	accesslog.filename          = "$POPONG_SVCROOT/log/webserver.access.log"
	accesslog.format            = "%h %V %u %t \\"%r\\" %>s %b \\"%{Referer}i\\" \\"%{User-Agent}i\\""
	
	mimetype.assign             = (
	  ".svg"          =>      "image/svg+xml",
	  ".jpg"          =>      "image/jpeg",
	  ".jpeg"         =>      "image/jpeg",
	  ".png"          =>      "image/png",
	  ".css"          =>      "text/css",
	  ".html"         =>      "text/html",
	  ".js"           =>      "text/javascript",
	  ".txt"          =>      "text/plain",
	  ".xml"          =>      "text/xml",
	  
	  ""              =>      "application/octet-stream",
	 )
	
	index-file.names            = ( "index.html"
	                              )
	dir-listing.activate        = "disable" 
	
	alias.url                   = (
	                              )
	url.rewrite-once = (
            # TODO separate module contents from URLs
            #"^/(intimacy|pithy)(/.*)?\$"  => "/#!\$2",
	)
	EOF
} >"$conf"

cd "$POPONG_SVCROOT"

# Prepare dirs
mkdir -p log

# Set base URL
host=`hostname -f`
if [ ! -e etc/base-url -o -w etc/base-url ]; then
    mkdir -p etc
    echo "http://$host:$Port" >etc/base-url
fi

# Show URLs to the server to be launched
echo "Server running at http://$host:$Port/"

# TODO switch to node.js?
# Launch web server in workspace
lighttpd -D -f "$conf"
